### ISSUE TITLE
Add OE wrappers and use buildroot toolchain(s)

### ISSUE THREAD

**Issue by tmagik** [sycuricon/riscv-spike-sdk#1]
In https://github.com/tmagik/freedom-u-sdk/tree/dev/oe I was attempting to (poorly) maintain most of the compatibility with the old makefile wrappers, and support OpenEmbedded as well.

I'd like to merge what you are doing here with that work, and strip out all the cruft.

One of the big crufty pieces I got rid of in my freedom-u-sdk fork was replacing the riscv-tools builds with the buildroot gcc versions.

Would this work for your use-cases, or do you need to do compiler hacking and then run spike?

**Comment by Phantom1003** [comment]
Yes, please create a new branch and push you ideas!
The reason I use the v1 FUSDK is because some of my project need to add new features in gcc, linux, and spike, using OE surely makes the work more clean and easy to use
