### ISSUE TITLE
Out of memory when running applications that need more than 2GB

### ISSUE THREAD

**Issue by sawansib** [sycuricon/riscv-spike-sdk#12]
Hi, great work and thank you for making my life easier :D

I want to run SPEC CPU 17 and some applications are failing because out-of-memory error. I notice that when booting up the kernel it says:-

``[    0.000000] Memory: 1982360K/2095104K available (3640K kernel code, 2736K rwdata, 2048K rodata, 4916K init, 259K bss, 112744K reserved, 0K cma-reserved)``

That means 2095104KB of ram that is around 2GB. How can we increase it?

Regards
Sawan

**Comment by Phantom1003** [comment]
Both spike and qemu support custom memory size.
For spike:
```
-m<n>                 Provide <n> MiB of target memory [default 2048]
  -m<a:m,b:n,...>       Provide memory regions of size m and n bytes
```
For qemu:
```
-m [size=]megs[,slots=n,maxmem=size]
                configure guest RAM
                size: initial amount of guest memory
                slots: number of hotplug slots (default: none)
                maxmem: maximum amount of guest memory (default: none)
```
Finally current RSS binds bbl with a deice tree under `/conf`, you can update the memory size in *.dts
Or, simply remove the --with-dts option in Makefile

**Comment by sawansib** [comment]
Hi,

Yes, I was already using the -m option for the Spike but I think that only change the address space of the Spike and not the kernel booting on it, which by default boots up with a 2GB of RAM on a 64bit machine.

After removing the --with-dts in the makefile, the RSS is stuck just after loading the RSS symbol. But updating the memory in the device tree works fine. 

Thank you for your response!

Sawan
