### ISSUE TITLE
Changing ISA to rv64g

### ISSUE THREAD

**Issue by sawansib** [sycuricon/riscv-spike-sdk#15]
Hi!

Changing the ISA to rv64g in the Makefile does not load the Linux correctly. 
It is stuck after the RSS. Any input will be helpful

Sawan

**Comment by Phantom1003** [comment]
Can you leave more detailed information?
The isa macro actually only influences toolchain and bbl compile, for linux you need to disable CONFIG_RISCV_ISA_C, for buildroot you need to disable R2_RISCV_ISA_CUSTOM_RVC config.

**Comment by sawansib** [comment]
```RISC-V Spike Simulator SDK
	  This SDK is based on SiFive Freedom U SDK.                    
	      ___           ___           ___     
	     /\  \         /\  \         /\  \    
	    /  \  \       /  \  \       /  \  \   
	   / /\ \  \     / /\ \  \     / /\ \  \  
	  /  \~\ \  \   _\ \~\ \  \   _\ \~\ \  \ 
	 / /\ \ \ \__\ /\ \ \ \ \__\ /\ \ \ \ \__\
	 \/_|  \/ /  / \ \ \ \ \/__/ \ \ \ \ \/__/
	    | |  /  /   \ \ \ \__\    \ \ \ \__\  
	    | |\/__/     \ \/ /  /     \ \/ /  /  
	    | |  |        \  /  /       \  /  /   
	     \|__|         \/__/         \/__/ 
```
The bootup is stuck at this point if I change the ISA macro to rv64g.
I noticed that you have already put a check in the Makefile to make the Linux according to the ISA specified (CONFIG_RISCV_ISA_C). I will test setting BR2_RISCV_ISA_CUSTOM_RVC to false and let you know.

**Comment by sawansib** [comment]
Setting BR2_RISCV_ISA_CUSTOM_RVC=n in  ./repo/buildroot/configs/hifive_unleashed_defconfig also gets the same result.

**Comment by Phantom1003** [comment]
You should also disable CONFIG_EFI, currently, CONFIG_RISCV_ISA_C is selected by CONFIG_EFI.
Simply disable CONFIG_RISCV_ISA_C will not work.
View the .config file or objdump the vmlinux under build/linux to check whether you turn off CONFIG_RISCV_ISA_C correctly.

**Comment by sawansib** [comment]
I tried setting CONFIG_EFI in ./repo/linux/arch/riscv/configs/defconfig, but i checked the vmlinux still have compressed instructions. Is there some other file I need to update? Also even if linux has some compressed instruction the spike should throw an exception but it is getting stuck so the issue might be something else?
My aim is to create a setup to run only rv64g RISC-V with Linux support. Although with current settings as well if I compile my application with ISA rv64g the compressed instructions that come are from the Linux and do you think the number of compressed in this case would be significant?

Thank you for your quick answers! I really appreciate it.

**Comment by Phantom1003** [comment]
Following is the linux config I used, delete the `build/linux` directory and re-make:
```
CONFIG_SOC_SIFIVE=y
CONFIG_RISCV_SBI_V01=y
CONFIG_SMP=y
# CONFIG_COMPACTION is not set
CONFIG_HZ_100=y
CONFIG_CROSS_COMPILE="riscv64-unknown-linux-gnu-"
CONFIG_DEFAULT_HOSTNAME="riscv-rss"
# CONFIG_CROSS_MEMORY_ATTACH is not set
CONFIG_NAMESPACES=y
CONFIG_BLK_DEV_INITRD=y
# CONFIG_RD_BZIP2 is not set
# CONFIG_RD_LZMA is not set
# CONFIG_RD_XZ is not set
# CONFIG_RD_LZO is not set
# CONFIG_RD_LZ4 is not set
CONFIG_EMBEDDED=y
# CONFIG_BLK_DEV_BSG is not set
CONFIG_PARTITION_ADVANCED=y
# CONFIG_IOSCHED_DEADLINE is not set
CONFIG_NET=y
CONFIG_PACKET=y
CONFIG_UNIX=y
CONFIG_INET=y
# CONFIG_INET_XFRM_MODE_TRANSPORT is not set
# CONFIG_INET_XFRM_MODE_TUNNEL is not set
# CONFIG_INET_XFRM_MODE_BEET is not set
# CONFIG_INET_DIAG is not set
# CONFIG_IPV6 is not set
CONFIG_DEVTMPFS=y
CONFIG_DEVTMPFS_MOUNT=y
# CONFIG_FIRMWARE_IN_KERNEL is not set
CONFIG_MTD=y
CONFIG_MTD_BLOCK_RO=y
CONFIG_MTD_M25P80=y
CONFIG_MTD_SPI_NOR=y
CONFIG_VIRTIO_BLK=y
CONFIG_EEPROM_AT24=y
CONFIG_BLK_DEV_SD=y
CONFIG_ATA=y
CONFIG_SATA_AHCI=y
CONFIG_SATA_SIL24=y
CONFIG_NETDEVICES=y
CONFIG_VIRTIO_NET=y
# CONFIG_VIRTIO_CONSOLE=y
CONFIG_MACB=y
CONFIG_MICROSEMI_PHY=y
# CONFIG_INPUT_KEYBOARD is not set
# CONFIG_INPUT_MOUSE is not set
CONFIG_VT=y
CONFIG_VT_CONSOLE=y
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
CONFIG_SERIAL_OF_PLATFORM=y
CONFIG_SERIAL_EARLYCON_RISCV_SBI=y
CONFIG_SERIAL_SIFIVE=y
# CONFIG_FB=y
# CONFIG_FRAMEBUFFER_CONSOLE is not set
# CONFIG_SERIAL_SIFIVE_CONSOL is not set
CONFIG_HVC_RISCV_SBI=y
# CONFIG_EFI is not set
# CONFIG_RISCV_ISA_C is not set
# CONFIG_HW_RANDOM=y
CONFIG_SPI=y
CONFIG_SPI_SIFIVE=y
CONFIG_POWER_RESET=y
CONFIG_POWER_RESET_GPIO_RESTART=y
CONFIG_MMC=y
CONFIG_MMC_SPI=y
CONFIG_CLK_U54_PRCI=y
CONFIG_CLK_GEMGXL_MGMT=y
# CONFIG_IOMMU_SUPPORT is not set
CONFIG_EXT4_FS=y
# CONFIG_PROC_PAGE_MONITOR is not set
CONFIG_TMPFS=y
# CONFIG_MISC_FILESYSTEMS is not set
# CONFIG_NETWORK_FILESYSTEMS is not set
CONFIG_CMDLINE_BOOL=y
CONFIG_CMDLINE="earlyprintk"
CONFIG_PRINTK_TIME=y
CONFIG_STRIP_ASM_SYMS=y
CONFIG_DEBUG_SECTION_MISMATCH=y
CONFIG_STACKTRACE=y
# CONFIG_CRYPTO_HW is not set
# CONFIG_ZERO_CALL_USED_REGS is not set
```
