### ISSUE TITLE
riscv64-unknown-linux-gnu-gcc not found error on latest master

### ISSUE THREAD

**Issue by RohanAhmed1** [sycuricon/riscv-spike-sdk#31]
I am trying to build it but getting this error.
 HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
scripts/Kconfig.include:39: C compiler 'riscv64-unknown-linux-gnu-gcc' not found
make[4]: *** [/projects/hydra/t_rahmed/riscv-spike-sdk/repo/linux/scripts/kconfig/Makefile:77: olddefconfig] Error 1
make[3]: *** [/projects/hydra/t_rahmed/riscv-spike-sdk/repo/linux/Makefile:697: olddefconfig] Error 2
make[2]: *** [/projects/hydra/t_rahmed/riscv-spike-sdk/repo/linux/Makefile:234: __sub-make] Error 2
make[2]: Leaving directory '/projects/hydra/t_rahmed/riscv-spike-sdk/build/linux'
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/projects/hydra/t_rahmed/riscv-spike-sdk/repo/linux'

I am following these steps
>> https://github.com/sycuricon/riscv-spike-sdk.git
>> git submodule init
>> git submodule upate
>> make

**Comment by HerrCai0907** [comment]
work around 
```diff
diff --git a/Makefile b/Makefile
index c952642..56b26cf 100644
--- a/Makefile
+++ b/Makefile
@@ -100,7 +100,7 @@ $(buildroot_initramfs_sysroot): $(buildroot_initramfs_tar)
        mkdir -p $(buildroot_initramfs_sysroot)
        tar -xpf $< -C $(buildroot_initramfs_sysroot) --exclude ./dev --exclude ./usr/share/locale
 
-$(linux_wrkdir)/.config: $(linux_defconfig) $(linux_srcdir)
+$(linux_wrkdir)/.config: $(toolchain_dest)/bin/$(target_linux)-gcc $(linux_defconfig) $(linux_srcdir)
        mkdir -p $(dir $@)
        cp -p $< $@
        $(MAKE) -C $(linux_srcdir) O=$(linux_wrkdir) ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- olddefconfig
```

**Comment by Phantom1003** [comment]
Hey @HerrCai0907, could you please open a pull request about this?
